# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme       : jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
locale      : en-US
title       : "Wandering Room"
name        : &name "HyunSoo Kim" # &name is a YAML anchor which can be *referenced later
baseurl     : # the subpath of your site, e.g. "/blog"
url         : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo        : "/assets/images/logo.png" # path of site logo, e.g. "/images/logo.png"
date_format : "%Y.%m.%d"

read_time   : false # reading time estimates, e.g. true
words_per_minute: # 200
mathjax     : # MathJax equations, e.g. true

google_fonts:
  - name: "Noto Sans KR"
    weights: "400,400i,700,700i"
  - name: "Nanum Gothic"
    weights: "400,400i,700,700i"
  - name: "Nanum Gothic Coding"
    weights: "400,400i,700,700i"

google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Outputting
paginate: 10 # amount of posts to show
paginate_path: /page/:num/
timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
  #category_archive_path: "/categories/#"
  #tag_archive_path: "/tags/#"
category_archive:
  type: liquid
  path: /category/
tag_archive:
  type: liquid
  path: /tag/

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
#whitelist:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji
#  - jekyll-include-cache

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
# excerpt_separator: "\n\n"

incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Front Matter Defaults
defaults:
  # home
  #- scope:
  #    path: "_posts"
  #    #type: posts
  #  values:
  #    layout: home
  #    share: true
  #    author_profile: true

  # _posts
  - scope:
      path: "_posts"
      #type: posts
    values:
      layout: post
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: true
      classes: wide
      toc: true
      
  # _pages
  - scope:
      path: "_pages"
      #type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

  # category and tag

# Site Author
author:
  name   : *name # *name is a YAML reference pointing to the &anchor earlier
  picture: "/assets/images/author.png"
  email: "willamettehd@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/hyunsoo-kim-willamette/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/WillametteKim"
    - label: "Facebook"
      icon: "fab fa-facebook-f"
      url: "https://facebook.com/willametteKim"
    - label: "Flickr"
      icon: "fab fa-flickr"
      url: "https://flickr.com/photos/145503508@N05/"

# Footer Links
footer_links:
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

github: [metadata]